# Generated by Django 5.2 on 2025-05-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero_potholes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='street_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='street_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
