# Generated by Django 5.2 on 2025-05-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero_potholes_app', '0002_report_street_height_alter_report_street_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
