# Generated by Django 5.2 on 2025-05-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero_potholes_app', '0003_alter_report_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(),
        ),
    ]
