# Generated by Django 5.2 on 2025-06-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero_potholes_app', '0004_alter_report_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSeverity',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='citizen_email',
            field=models.EmailField(default='placeholder@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='citizen_first_name',
            field=models.CharField(default='placeholder@example.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='citizen_last_name',
            field=models.CharField(default='placeholder@example.com', max_length=50),
            preserve_default=False,
        ),
    ]
