# Generated by Django 5.2 on 2025-06-26 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero_potholes_app', '0005_reportseverity_report_citizen_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zero_potholes_app.reportseverity'),
        ),
    ]
