# Generated by Django 5.2 on 2025-07-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zero_potholes_app', '0006_report_severity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='assigned_moderator',
        ),
    ]
